# Generated by Django 3.1.7 on 2021-05-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_profile',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='consultant_profile',
            name='role_id',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
